export const IDEA_REQUEST_SUCCESS = 'IDEA_REQUEST_SUCCESS';
export const IDEA_REQUEST_FAILURE = 'IDEA_REQUEST_FAILURE';
export const IDEA_REQUEST = 'IDEA_REQUEST';
export const IDEA_DELETE_REQUEST = 'IDEA_DELETE_REQUEST';
export const EDIT_IDEA_REQUEST = 'EDIT_IDEA_REQUEST';
export const CREATE_IDEA_REQUEST = 'CREATE_IDEA_REQUEST';
export const STORE_CURRENT_IDEA = 'STORE_CURRENT_IDEA';
